import { useState } from "react";
import { Title, Text, Accordion, Modal } from "rizzui";
import { ChevronDown } from "lucide-react";

const FAQSection = () => {
  // FAQ data
  const faqs = [
    {
      question: "How does MarketGenius analyze competitor websites?",
      answer:
        "MarketGenius uses advanced web scraping and natural language processing to analyze top-ranking websites for your target keywords. We examine content structure, keyword density, backlink profiles, and user engagement metrics to provide you with actionable insights.",
    },
    {
      question: "Is the content generated by MarketGenius original and unique?",
      answer:
        "Yes, all content generated by MarketGenius is 100% original. Our AI analyzes successful content strategies but creates new content from scratch, ensuring it passes plagiarism checks while being optimized for search engines and user engagement.",
    },
    {
      question: "How accurate are the analytics and insights?",
      answer:
        "MarketGenius provides high-accuracy insights based on real-time data from top search results. Our algorithms have been trained on millions of successful websites to identify patterns that lead to higher rankings. We regularly update our models to ensure they remain accurate with the latest search algorithm changes.",
    },
    {
      question: "Can I use MarketGenius for multiple websites or projects?",
      answer:
        "Absolutely! Our Professional and Enterprise plans allow you to manage multiple websites and projects from a single dashboard. You can compare performance across different sites and apply successful strategies from one project to another with just a few clicks.",
    },
    {
      question: "How long does a typical analysis take to complete?",
      answer:
        "Most keyword analyses complete within 2-5 minutes, depending on the competition level and number of websites being analyzed. For more comprehensive market analyses, including full content audits and opportunity identification, the process may take 10-15 minutes.",
    },
    {
      question: "Do you offer a free trial?",
      answer:
        "Yes, we offer a 14-day free trial that gives you access to most features of our platform with some usage limitations. No credit card is required to start your trial, and you can upgrade to a paid plan at any time to unlock full functionality.",
    },
  ];
  const [isOpen, setIsOpen] = useState(false);
  // Custom styles for accordion

  return (
    <section id="faq" className="bg-gray-900 py-16 md:py-24">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <Modal isOpen={isOpen} onClose={() => setIsOpen(false)}>
            <div className="p-6 space-y-6">
              <h1 className="text-red-900 text-3xl">We are sorry 😒</h1>
              <p>Support is not yet implemented</p>
            </div>
          </Modal>
          <Title className="text-3xl md:text-4xl font-bold text-white mb-4">
            Frequently Asked Questions
          </Title>
          <Text className="text-gray-300 text-lg max-w-2xl mx-auto">
            Everything you need to know about MarketGenius and how it can help
            you outrank your competition.
          </Text>
        </div>

        <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-2xl p-1">
          <div>
            {faqs.map((faqs, index) => {
              return (
                <Accordion
                  key={index}
                  className="mx-8 border-b last-of-type:border-b-0"
                >
                  <Accordion.Header>
                    {({ open }) => (
                      <div className="flex w-full cursor-pointer items-center justify-between py-5 text-xl font-semibold">
                        {faqs.question}
                        <ChevronDown
                          className={`h-5 w-5 -rotate-90 transform transition-transform duration-300 ${
                            open && "-rotate-0"
                          }`}
                        />
                      </div>
                    )}
                  </Accordion.Header>
                  <Accordion.Body className="mb-7">
                    {faqs.answer}
                  </Accordion.Body>
                </Accordion>
              );
            })}
          </div>
        </div>

        <div className="mt-12 text-center">
          <Text className="text-gray-400 mb-4">
            Still have questions? We're here to help!
          </Text>
          <div
            onClick={() => setIsOpen(true)}
            className="inline-flex items-center text-blue-400 hover:text-blue-300 font-medium"
          >
            Contact our support team
            <ChevronDown className="ml-2 rotate-270" size={16} />
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
